name: Doctest

on:
  push:
    branches:
      - master
  pull_request:
    if: github.event.pull_request.draft == false
    branches:
      - '**'

jobs:

  build-and-test:
    if: github.event.pull_request.draft == false
    name: Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: install pints
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
          python -m pip install .[docs]

      - name: run doctest
        run: |
          python run-tests.py --doctest
